project_id = "xrzxchkxeofbgkuypzqo"

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.notify-zapier-donation]
verify_jwt = false

[functions.notify-zapier-volunteer]
verify_jwt = false

[functions.send-volunteer-confirmation]
verify_jwt = false

[functions.send-volunteer-reminders]
verify_jwt = false